import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { openApp } from './app'

test('preserva rascunho após erro, permite corrigir e não duplica recorrências no retry', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await openApp(page)
  if (testInfo.project.name === 'Mobile Chrome') await page.setViewportSize({ width: 320, height: 740 })
  const topbar = await new AxeBuilder({ page }).include('.finance-topbar').analyze()
  expect(topbar.violations).toEqual([])
  await page.getByRole('button', { name: testInfo.project.name === 'Desktop Chrome' ? 'Planilha' : 'Lançamentos', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Planilha', exact: true, level: 1 })).toBeVisible()
  expect(await page.locator('.topbar-heading h1').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.getByRole('button', { name: 'Lista', exact: true }).click()
  await page.getByRole('button', { name: 'Novo lançamento', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Novo lançamento' })
  const title = `Revisão retry ${testInfo.project.name}`
  await dialog.getByLabel('Descrição', { exact: true }).fill(title)
  await dialog.getByLabel('Valor (R$)', { exact: true }).fill('inválido')
  await dialog.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(dialog.getByLabel('Valor (R$)', { exact: true })).toBeFocused()
  await expect(dialog.getByRole('alert')).toContainText('valor válido')
  await dialog.getByLabel('Valor (R$)', { exact: true }).fill('1.234,56')
  await dialog.getByLabel('Recorrência (meses)', { exact: true }).fill('2')
  await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(dialog.getByText('Descartar as alterações deste lançamento?')).toBeVisible()
  await dialog.getByRole('button', { name: 'Continuar editando' }).click()
  await expect(dialog.getByLabel('Descrição', { exact: true })).toHaveValue(title)

  await page.route('**/api/entries/batch', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ message: 'Falha simulada' }) }))
  await dialog.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(dialog.getByText(/Você pode tentar salvar novamente/)).toBeVisible()
  await expect(dialog.getByLabel('Valor (R$)', { exact: true })).toHaveValue('1.234,56')
  const accessibility = await new AxeBuilder({ page }).include('[role="dialog"]').analyze()
  expect(accessibility.violations).toEqual([])
  expect(await dialog.locator('.sheet-body').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: `docs/revisao-2026-09-04/evidencias/etapas234-editor-${testInfo.project.name.replaceAll(' ', '-')}.png`, animations: 'disabled' })
  await page.unroute('**/api/entries/batch')
  await dialog.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const result = await page.request.get('/api/bootstrap?key=demo-finance-key')
  const entries = (await result.json()).entries.filter((entry: { title: string }) => entry.title === title)
  expect(entries).toHaveLength(2)
  expect(entries.every((entry: { amount: number }) => entry.amount === 1234.56)).toBe(true)
})

test('preserva mês, busca e modo na URL e oferece cards acessíveis em tela estreita', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await openApp(page)
  if (testInfo.project.name === 'Mobile Chrome') await page.setViewportSize({ width: 320, height: 740 })
  await page.getByRole('button', { name: testInfo.project.name === 'Desktop Chrome' ? 'Planilha' : 'Lançamentos', exact: true }).click()
  await page.getByLabel('Buscar lançamentos', { exact: true }).fill('Aluguel')
  await expect(page).toHaveURL(/q=Aluguel/)
  const location = page.url()
  await page.reload()
  await expect(page.getByLabel('Buscar lançamentos', { exact: true })).toHaveValue('Aluguel')
  await page.getByRole('button', { name: testInfo.project.name === 'Desktop Chrome' ? 'Dashboard' : 'Início', exact: true }).click()
  await expect(page).toHaveURL(/screen=dashboard/)
  await expect(page.getByLabel('Buscar lançamentos', { exact: true })).not.toBeVisible()
  await page.goBack()
  await expect(page).toHaveURL(location)
  await expect(page.getByLabel('Buscar lançamentos', { exact: true })).toHaveValue('Aluguel')
  if (testInfo.project.name !== 'Desktop Chrome') {
    await expect(page.locator('.mcard')).toHaveCount(1)
    const scan = await new AxeBuilder({ page }).include('.mcard').analyze()
    expect(scan.violations).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.screenshot({ path: `docs/revisao-2026-09-04/evidencias/etapas234-planilha-${testInfo.project.name.replaceAll(' ', '-')}.png`, fullPage: true, animations: 'disabled' })
})
